main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.0.10.376
api-version: '1.18'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
permissions:
  stubfxplugin.*:
    default: op