main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.0
api-version: '1.17'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
  draw:
    description: An example command
    usage: /draw
  jesus:
    description: An example command
    usage: /jesus
  drill:
    description: An example command
    usage: /drill
  clearchunk:
    description: An example command
    usage: /clearchunk
  stopcommand:
    description: An example command
    usage: /stopcommand
default-permission: op