main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.1.0
api-version: '1.18'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
  creep:
    description: An example command
    usage: /creep
    permission: stubfxplugin.creep
    permission-message: You don't have the stubFXplugin.sculktrap permission.
permissions:
  stubfxplugin.*:
    default: op