main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.0.10.523
api-version: '1.18'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
  config:
    description: An example command
    usage: /config
    permission: stubfxplugin.config
    permission-message: You don't have the stubFXplugin.config permission.
permissions:
  stubfxplugin.*:
    default: op