main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.0
api-version: '1.17'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
  draw:
    description: An example command
    usage: /draw
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.
  jesus:
    description: An example command
    usage: /jesus
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.
  drill:
    description: An example command
    usage: /drill
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.
  clearchunk:
    description: An example command
    usage: /clearchunk
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.
  stopcommand:
    description: An example command
    usage: /stopcommand
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.