main: com.minecrowd.plugin.Main
name: minecrowd
version: 1.0.10.1161
api-version: '1.20'
author: stubfx
description: A simple stream plugin made by me.
commands:
  command:
    description: An example command
    usage: /command
    permission: minecrowd.command
    permission-message: You don't have the minecrowd.command permission.
permissions:
  minecrowd.*:
    default: op