main: com.stubfx.plugin.Main
name: stubFXplugin
version: 1.0.10.710
api-version: '1.19'
author: stubFX
description: A simple stream plugin made at twitch.tv/stubfx
commands:
  command:
    description: An example command
    usage: /command
    permission: stubfxplugin.command
    permission-message: You don't have the stubFXplugin.command permission.
permissions:
  stubfxplugin.*:
    default: op