commands:
  spawn:
    title: Spawn
    cooldown: 60
    enable: true
    silent: false
  
  dropit:
    title: Drop It
    cooldown: 60
    enable: true
    silent: false
  
  levitate:
    title: Levitate
    cooldown: 60
    enable: true
    silent: false
  
  fire:
    title: Fire
    cooldown: 60
    enable: true
    silent: false
  
  diamonds:
    title: Diamonds
    cooldown: 60
    enable: false
    silent: false
  
  chickens:
    title: Chickens!
    cooldown: 60
    enable: true
    silent: false
  
  knock:
    title: Knock
    cooldown: 60
    enable: true
    silent: false
  
  panic:
    title: Panic
    cooldown: 60
    enable: true
    silent: true
  
  tree:
    title: Tree
    cooldown: 60
    enable: true
    silent: false
  
  speedy:
    title: Speedy
    cooldown: 60
    enable: true
    silent: false
  
  heal:
    title: Heal
    cooldown: 60
    enable: true
    silent: false
  
  hungry:
    title: Hungry
    cooldown: 60
    enable: true
    silent: false
  
  feed:
    title: Feed
    cooldown: 60
    enable: true
    silent: false
  
  wallhack:
    title: Wallhack
    cooldown: 60
    enable: true
    silent: false
  
  superman:
    title: Superman
    cooldown: 60
    enable: true
    silent: false
  
  normalman:
    title: Normalman
    cooldown: 60
    enable: true
    silent: false
  
  water:
    title: Water
    cooldown: 60
    enable: true
    silent: false
  
  woollify:
    title: Woollify
    cooldown: 60
    enable: true
    silent: false
  
  randomblock:
    title: Random block
    cooldown: 60
    enable: true
    silent: false
  
  neverfall:
    title: Never fall
    cooldown: 60
    enable: true
    silent: false
  
  armored:
    title: armored
    cooldown: 60
    enable: true
    silent: false
  
  tothenether:
    title: To the nether
    cooldown: 60
    enable: true
    silent: false
  
  totheoverworld:
    title: To the overworld
    cooldown: 60
    enable: true
    silent: false
  
  bob:
    title: BoB
    cooldown: 60
    enable: true
    silent: false
  
  nukemobs:
    title: Nuke Mobs
    cooldown: 60
    enable: true
    silent: false
  
  dinnerbone:
    title: Dinnerbone
    cooldown: 60
    enable: true
    silent: false
  
  craftingtable:
    title: Crafting table
    cooldown: 60
    enable: true
    silent: false
  
  anvil:
    title: Anvil
    cooldown: 60
    enable: true
    silent: false
  
  ihaveit:
    title: I have it
    cooldown: 60
    enable: true
    silent: false
  
  paint:
    title: Paint
    cooldown: 60
    enable: true
    silent: false
  
  goingdown:
    title: Going down
    cooldown: 60
    enable: true
    silent: false


